# Generated by Django 5.1.4 on 2025-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity Sensor 1')),
                ('temperature1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature Sensor 1')),
                ('humidity2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity Sensor 2')),
                ('temperature2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature Sensor 2')),
                ('humidity_average', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity Average')),
                ('temperature_average', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature Average')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Records',
                'verbose_name_plural': 'Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
