# Generated by Django 5.1.4 on 2025-01-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_time', models.CharField(choices=[('5M', '5 minutos'), ('10M', '10 minutos'), ('30M', '30 minutos'), ('1H', '1 hora'), ('2H', '2 horas')], default='5M', max_length=3, verbose_name='Tiempo de muestreo')),
                ('temperature_min_1', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Temperatura Mínima Sensor 1')),
                ('temperature_max_1', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Temperatura Máxima Sensor 1')),
                ('humidity_min_1', models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='Humedad Mínima Sensor 1')),
                ('humidity_max_1', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Humedad Máxima Sensor 1')),
                ('temperature_min_2', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Temperatura Mínima Sensor 2')),
                ('temperature_max_2', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Temperatura Máxima Sensor 2')),
                ('humidity_min_2', models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='Humedad Mínima Sensor 2')),
                ('humidity_max_2', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Humedad Máxima Sensor 2')),
                ('temperature_min_alert', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Temperatura Mínima Alerta')),
                ('temperature_max_alert', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Temperatura Máxima Alerta')),
                ('humidity_min_alert', models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='Humedad Mínima Alerta')),
                ('humidity_max_alert', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Humedad Máxima Alerta')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['timestamp'], 'verbose_name': 'Registros', 'verbose_name_plural': 'Registros'},
        ),
    ]
