# Generated by Django 5.1.4 on 2025-02-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_configuration_alter_records_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sampling_time',
            field=models.CharField(choices=[('15S', '15 segundos'), ('30S', '30 segundos'), ('1M', '1 minuto'), ('5M', '5 minutos'), ('10M', '10 minutos'), ('30M', '30 minutos'), ('1H', '1 hora'), ('2H', '2 horas')], default='5M', max_length=3, verbose_name='Tiempo de muestreo'),
        ),
    ]
